<?php
/**
 * EventPhotos.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.0 (https://modulestudio.de).
 */

namespace RK\EventPhotosModule\Form\Type\QuickNavigation;

use RK\EventPhotosModule\Form\Type\QuickNavigation\Base\AbstractAlbumQuickNavType;

/**
 * Album quick navigation form type implementation class.
 */
class AlbumQuickNavType extends AbstractAlbumQuickNavType
{
    // feel free to extend the base form type class here
}
