<?php
/**
 * EventPhotos.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.0 (https://modulestudio.de).
 */

namespace RK\EventPhotosModule\Helper\Base;

use IntlDateFormatter;
use Symfony\Component\HttpFoundation\RequestStack;
use Zikula\Common\Translator\TranslatorInterface;
use RK\EventPhotosModule\Entity\AlbumEntity;
use RK\EventPhotosModule\Entity\AlbumItemEntity;
use RK\EventPhotosModule\Helper\ListEntriesHelper;

/**
 * Entity display helper base class.
 */
abstract class AbstractEntityDisplayHelper
{
    /**
     * @var TranslatorInterface
     */
    protected $translator;

    /**
     * @var ListEntriesHelper Helper service for managing list entries
     */
    protected $listEntriesHelper;

    /**
     * @var IntlDateFormatter Formatter for dates
     */
    protected $dateFormatter;

    /**
     * EntityDisplayHelper constructor.
     *
     * @param TranslatorInterface $translator        Translator service instance
     * @param RequestStack        $requestStack      RequestStack service instance
     * @param ListEntriesHelper   $listEntriesHelper Helper service for managing list entries
     */
    public function __construct(
        TranslatorInterface $translator,
        RequestStack $requestStack,
        ListEntriesHelper $listEntriesHelper
    ) {
        $this->translator = $translator;
        $this->listEntriesHelper = $listEntriesHelper;
        $locale = null !== $requestStack->getCurrentRequest() ? $requestStack->getCurrentRequest()->getLocale() : null;
        $this->dateFormatter = new IntlDateFormatter($locale, IntlDateFormatter::NONE, IntlDateFormatter::NONE);
    }

    /**
     * Returns the formatted title for a given entity.
     *
     * @param object $entity The given entity instance
     *
     * @return string The formatted title
     */
    public function getFormattedTitle($entity)
    {
        if ($entity instanceof AlbumEntity) {
            return $this->formatAlbum($entity);
        }
        if ($entity instanceof AlbumItemEntity) {
            return $this->formatAlbumItem($entity);
        }
    
        return '';
    }
    
    /**
     * Returns the formatted title for a given entity.
     *
     * @param AlbumEntity $entity The given entity instance
     *
     * @return string The formatted title
     */
    protected function formatAlbum(AlbumEntity $entity)
    {
        return $this->translator->__f('%albumDate%, %albumTitle%', [
            '%albumDate%' => $this->dateFormatter->formatObject($entity->getAlbumDate(), [IntlDateFormatter::SHORT, IntlDateFormatter::NONE]),
            '%albumTitle%' => $entity->getAlbumTitle()
        ]);
    }
    
    /**
     * Returns the formatted title for a given entity.
     *
     * @param AlbumItemEntity $entity The given entity instance
     *
     * @return string The formatted title
     */
    protected function formatAlbumItem(AlbumItemEntity $entity)
    {
        return $this->translator->__f('%imageTitle%', [
            '%imageTitle%' => $entity->getImageTitle()
        ]);
    }
    
    /**
     * Returns name of the field used as title / name for entities of this repository.
     *
     * @param string $objectType Name of treated entity type
     *
     * @return string Name of field to be used as title
     */
    public function getTitleFieldName($objectType)
    {
        if ($objectType == 'album') {
            return 'albumTitle';
        }
        if ($objectType == 'albumItem') {
            return 'copyright';
        }
    
        return '';
    }
    
    /**
     * Returns name of the field used for describing entities of this repository.
     *
     * @param string $objectType Name of treated entity type
     *
     * @return string Name of field to be used as description
     */
    public function getDescriptionFieldName($objectType)
    {
        if ($objectType == 'album') {
            return 'albumDescription';
        }
        if ($objectType == 'albumItem') {
            return 'imageDescription';
        }
    
        return '';
    }
    
    /**
     * Returns name of first upload field which is capable for handling images.
     *
     * @param string $objectType Name of treated entity type
     *
     * @return string Name of field to be used for preview images
     */
    public function getPreviewFieldName($objectType)
    {
        if ($objectType == 'albumItem') {
            return 'image';
        }
    
        return '';
    }
    
    /**
     * Returns name of the date(time) field to be used for representing the start
     * of this object. Used for providing meta data to the tag module.
     *
     * @param string $objectType Name of treated entity type
     *
     * @return string Name of field to be used as date
     */
    public function getStartDateFieldName($objectType)
    {
        if ($objectType == 'album') {
            return 'createdDate';
        }
        if ($objectType == 'albumItem') {
            return 'createdDate';
        }
    
        return '';
    }
}
