services:
    # Helper services
    rk_eventphotos_module.category_helper:
        class: RK\EventPhotosModule\Helper\CategoryHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@logger"
            - "@zikula_users_module.current_user"
            - "@zikula_categories_module.category_registry_repository"
            - "@zikula_categories_module.api.category_permission"
    
    rk_eventphotos_module.collection_filter_helper:
        class: RK\EventPhotosModule\Helper\CollectionFilterHelper
        arguments:
            - "@request_stack"
            - "@zikula_users_module.current_user"
            - "@rk_eventphotos_module.category_helper"
            - "@=service('zikula_extensions_module.api.variable').get('RKEventPhotosModule', 'showOnlyOwnEntries', false)"
    
    rk_eventphotos_module.controller_helper:
        class: RK\EventPhotosModule\Helper\ControllerHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@router"
            - "@form.factory"
            - "@zikula_extensions_module.api.variable"
            - "@rk_eventphotos_module.entity_factory"
            - "@rk_eventphotos_module.collection_filter_helper"
            - "@rk_eventphotos_module.model_helper"
            - "@rk_eventphotos_module.image_helper"
            - "@rk_eventphotos_module.feature_activation_helper"
    
    rk_eventphotos_module.entity_display_helper:
        class: RK\EventPhotosModule\Helper\EntityDisplayHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@rk_eventphotos_module.listentries_helper"
    
    rk_eventphotos_module.feature_activation_helper:
        class: RK\EventPhotosModule\Helper\FeatureActivationHelper
    
    rk_eventphotos_module.hook_helper:
        class: RK\EventPhotosModule\Helper\HookHelper
        arguments:
            - "@hook_dispatcher"
    
    rk_eventphotos_module.image_helper:
        class: RK\EventPhotosModule\Helper\ImageHelper
        arguments:
            - "@translator.default"
            - "@session"
            - "@zikula_extensions_module.api.variable"
    
    rk_eventphotos_module.listentries_helper:
        class: RK\EventPhotosModule\Helper\ListEntriesHelper
        arguments:
            - "@translator.default"
    
    rk_eventphotos_module.model_helper:
        class: RK\EventPhotosModule\Helper\ModelHelper
        arguments:
            - "@rk_eventphotos_module.entity_factory"
    
    rk_eventphotos_module.search_helper:
        class: RK\EventPhotosModule\Helper\SearchHelper
        arguments:
            - "@translator.default"
            - "@zikula_permissions_module.api.permission"
            - "@session"
            - "@request_stack"
            - "@rk_eventphotos_module.entity_factory"
            - "@rk_eventphotos_module.controller_helper"
            - "@rk_eventphotos_module.entity_display_helper"
            - "@rk_eventphotos_module.feature_activation_helper"
            - "@rk_eventphotos_module.category_helper"
        tags:
            - { name: zikula.searchable_module, bundleName: RKEventPhotosModule }
    
    rk_eventphotos_module.translatable_helper:
        class: RK\EventPhotosModule\Helper\TranslatableHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_settings_module.locale_api"
            - "@rk_eventphotos_module.entity_factory"
    
    rk_eventphotos_module.upload_helper:
        class: RK\EventPhotosModule\Helper\UploadHelper
        arguments:
            - "@translator.default"
            - "@filesystem"
            - "@session"
            - "@logger"
            - "@zikula_users_module.current_user"
            - "@=service('zikula_extensions_module.api.variable').getAll('RKEventPhotosModule')"
            - "%datadir%"
    
    rk_eventphotos_module.view_helper:
        class: RK\EventPhotosModule\Helper\ViewHelper
        arguments:
            - "@twig"
            - "@twig.loader"
            - "@request_stack"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_core.common.theme.pagevars"
            - "@rk_eventphotos_module.controller_helper"
    
    rk_eventphotos_module.workflow_helper:
        class: RK\EventPhotosModule\Helper\WorkflowHelper
        arguments:
            - "@translator.default"
            - "@workflow.registry"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_users_module.current_user"
            - "@rk_eventphotos_module.entity_factory"
            - "@rk_eventphotos_module.listentries_helper"
