<?php
/**
 * EventPhotos.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.0 (https://modulestudio.de).
 */

namespace RK\EventPhotosModule\Form\Type;

use RK\EventPhotosModule\Form\Type\Base\AbstractAlbumItemType;

/**
 * Album item editing form type implementation class.
 */
class AlbumItemType extends AbstractAlbumItemType
{
    // feel free to extend the album item editing form type class here
}
