<?php
/**
 * EventPhotos.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.0 (https://modulestudio.de).
 */

namespace RK\EventPhotosModule;

use RK\EventPhotosModule\Base\AbstractEventPhotosEvents;

/**
 * Events definition implementation class.
 */
class EventPhotosEvents extends AbstractEventPhotosEvents
{
    // feel free to extend the events definition here
}
