<?php
/**
 * EventPhotos.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.0 (https://modulestudio.de).
 */

namespace RK\EventPhotosModule;

use RK\EventPhotosModule\Base\AbstractEventPhotosModuleInstaller;

/**
 * Installer implementation class.
 */
class EventPhotosModuleInstaller extends AbstractEventPhotosModuleInstaller
{
    // feel free to extend the installer here
public function install()

{

    $result = parent::install();

    if (true === $result) {

        // eigene Werte setzen
        // set up all our vars with initial values
        // $this->setVar('albumEntriesPerPage', 10);
        // $this->setVar('linkOwnAlbumsOnAccountPage', true);
        // $this->setVar('albumItemEntriesPerPage', 10);
        // $this->setVar('linkOwnAlbumItemsOnAccountPage', true);
        $this->setVar('enableShrinkingForAlbumItemImage', true);
        $this->setVar('shrinkWidthAlbumItemImage', 2000);
        $this->setVar('shrinkHeightAlbumItemImage', 2000);
        $this->setVar('thumbnailModeAlbumItemImage', 'inset');
        $this->setVar('thumbnailWidthAlbumItemImageView', 150);
        $this->setVar('thumbnailHeightAlbumItemImageView', 150);
        $this->setVar('thumbnailWidthAlbumItemImageDisplay', 300);
        $this->setVar('thumbnailHeightAlbumItemImageDisplay', 300);
        $this->setVar('thumbnailWidthAlbumItemImageEdit', 180);
        $this->setVar('thumbnailHeightAlbumItemImageEdit', 180);
        // $this->setVar('enabledFinderTypes', 'album###albumItem');
		
    }

    return $result;
}
}
