<?php
/**
 * EventPhotos.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.0 (https://modulestudio.de).
 */

namespace RK\EventPhotosModule\Block;

use RK\EventPhotosModule\Block\Base\AbstractItemBlock;

/**
 * Generic item detail block implementation class.
 */
class ItemBlock extends AbstractItemBlock
{
    // feel free to extend the item detail block here
}
