<?php
/**
 * EventPhotos.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.0 (https://modulestudio.de).
 */

namespace RK\EventPhotosModule\Event;

use RK\EventPhotosModule\Event\Base\AbstractFilterAlbumItemEvent;

/**
 * Event implementation class for filtering album item processing.
 */
class FilterAlbumItemEvent extends AbstractFilterAlbumItemEvent
{
    // feel free to extend the event class here
}
