<?php
/**
 * EventPhotos.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.0 (https://modulestudio.de).
 */

namespace RK\EventPhotosModule\Listener;

use RK\EventPhotosModule\Listener\Base\AbstractGroupListener;

/**
 * Event handler implementation class for group-related events.
 */
class GroupListener extends AbstractGroupListener
{
    // feel free to enhance the parent methods
}
