<?php
/**
 * EventPhotos.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.0 (https://modulestudio.de).
 */

namespace RK\EventPhotosModule\Entity;

use RK\EventPhotosModule\Entity\Base\AbstractAlbumTranslationEntity as BaseEntity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing album translations.
 *
 * This is the concrete translation class for album entities.
 *
 * @ORM\Entity(repositoryClass="RK\EventPhotosModule\Entity\Repository\AlbumTranslationRepository")
 * @ORM\Table(name="rk_event_album_translation",
 *     indexes={
 *         @ORM\Index(name="translations_lookup_idx", columns={
 *             "locale", "object_class", "foreign_key"
 *         })
 *     }
 * )
 */
class AlbumTranslationEntity extends BaseEntity
{
    // feel free to add your own methods here
}
