<?php
/**
 * EventPhotos.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.0 (https://modulestudio.de).
 */

namespace RK\EventPhotosModule\Entity;

use RK\EventPhotosModule\Entity\Base\AbstractAlbumEntity as BaseEntity;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the concrete entity class for album entities.
 * @Gedmo\TranslationEntity(class="RK\EventPhotosModule\Entity\AlbumTranslationEntity")
 * @ORM\Entity(repositoryClass="RK\EventPhotosModule\Entity\Repository\AlbumRepository")
 * @ORM\Table(name="rk_event_album",
 *     indexes={
 *         @ORM\Index(name="workflowstateindex", columns={"workflowState"})
 *     }
 * )
 */
class AlbumEntity extends BaseEntity
{
    // feel free to add your own methods here
}
