<?php
/**
 * EventPhotos.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.0 (https://modulestudio.de).
 */

namespace RK\EventPhotosModule\DependencyInjection;

use RK\EventPhotosModule\DependencyInjection\Base\AbstractRKEventPhotosExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class RKEventPhotosExtension extends AbstractRKEventPhotosExtension
{
    // custom enhancements can go here
}
