<?php
/**
 * EventPhotos.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.0 (https://modulestudio.de).
 */

namespace RK\EventPhotosModule\HookSubscriber;

use RK\EventPhotosModule\HookSubscriber\Base\AbstractAlbumItemUiHooksSubscriber;

/**
 * Implementation class for ui hooks subscriber.
 */
class AlbumItemUiHooksSubscriber extends AbstractAlbumItemUiHooksSubscriber
{
    // feel free to add your own convenience methods here
}
