<?php
/**
 * EventPhotos.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.0 (https://modulestudio.de).
 */

namespace RK\EventPhotosModule\Entity\Base;

use Doctrine\ORM\Mapping as ORM;
use Zikula\CategoriesModule\Entity\AbstractCategoryAssignment;

/**
 * Entity extension domain class storing album item categories.
 *
 * This is the base category class for album item entities.
 */
abstract class AbstractAlbumItemCategoryEntity extends AbstractCategoryAssignment
{
    /**
     * @ORM\ManyToOne(targetEntity="\RK\EventPhotosModule\Entity\AlbumItemEntity", inversedBy="categories")
     * @ORM\JoinColumn(name="entityId", referencedColumnName="id")
     * @var \RK\EventPhotosModule\Entity\AlbumItemEntity
     */
    protected $entity;
    
    /**
     * Get reference to owning entity.
     *
     * @return \RK\EventPhotosModule\Entity\AlbumItemEntity
     */
    public function getEntity()
    {
        return $this->entity;
    }
    
    /**
     * Set reference to owning entity.
     *
     * @param \RK\EventPhotosModule\Entity\AlbumItemEntity $entity
     */
    public function setEntity(/*\RK\EventPhotosModule\Entity\AlbumItemEntity */$entity)
    {
        $this->entity = $entity;
    }
}
