<?php
/**
 * EventPhotos.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.0 (https://modulestudio.de).
 */

namespace RK\EventPhotosModule\Entity\Repository;

use RK\EventPhotosModule\Entity\Repository\Base\AbstractAlbumItemCategoryRepository;

/**
 * Repository class used to implement own convenience methods for performing certain DQL queries.
 *
 * This is the concrete repository class for album item category entities.
 */
class AlbumItemCategoryRepository extends AbstractAlbumItemCategoryRepository
{
    // feel free to add your own methods here
}
