<?php
/**
 * EventPhotos.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.0 (https://modulestudio.de).
 */

namespace RK\EventPhotosModule\Form\Handler\AlbumItem;

use RK\EventPhotosModule\Form\Handler\AlbumItem\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of editing forms.
 * It aims on the album item object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
