<?php
/**
 * EventPhotos.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 1.3.0 (https://modulestudio.de).
 */

namespace RK\EventPhotosModule\Entity\Factory\Base;

use RK\EventPhotosModule\Entity\AlbumEntity;
use RK\EventPhotosModule\Entity\AlbumItemEntity;

/**
 * Entity initialiser class used to dynamically apply default values to newly created entities.
 */
abstract class AbstractEntityInitialiser
{
    /**
     * Initialises a given album instance.
     *
     * @param AlbumEntity $entity The newly created entity instance
     *
     * @return AlbumEntity The updated entity instance
     */
    public function initAlbum(AlbumEntity $entity)
    {

        return $entity;
    }

    /**
     * Initialises a given albumItem instance.
     *
     * @param AlbumItemEntity $entity The newly created entity instance
     *
     * @return AlbumItemEntity The updated entity instance
     */
    public function initAlbumItem(AlbumItemEntity $entity)
    {

        return $entity;
    }

}
